### ISSUE TITLE
TotalShards in LLManagerConfig is unnecessary.

### ISSUE THREAD

**Issue by SolarysDev** [Devoxin/SharpLink#10]
LavaLinkManager's only constructor takes one DiscordSocketClient, which doesn't support sharding, yet you can configure the total shards in the LLManagerConfig.

Unless we're supposed to give each individual client its own manager, which defeats the point of TotalShards in the first place.

**Comment by NovusTheory** [comment]
Lavalink needs a client for each discord gateway connection and the point of Total Shards is that lavalink requires it's passed and yes if you shard with multiple programs (which big bots do) it doesn't make total shards pointless.
