### ISSUE TITLE
Disconnected handlers blocking indefinitely

### ISSUE THREAD

**Issue by jaxc83** [Devoxin/SharpLink#19]
The `DiscordShardedClient` and `DiscordSocketClient` disconnected handlers are entering a semaphore(1) and calling a method that ends up indefinitely waiting to enter the same semaphore, as shown below:

Disconnected handler enters `playerLock` and calls `DisconnectAsync` on a player
https://github.com/Devoxin/SharpLink/blob/f763ff7f0e6648c60de0e3d4da2eb60e8d45d12e/SharpLink/LavalinkManager.cs#L107-L116
`DisconnectAsync` calls `RemovePlayerAsync`
https://github.com/Devoxin/SharpLink/blob/f763ff7f0e6648c60de0e3d4da2eb60e8d45d12e/SharpLink/LavalinkPlayer.cs#L42-L46
`RemovePlayerAsync` waits indefinitely trying to enter `playerLock`
https://github.com/Devoxin/SharpLink/blob/f763ff7f0e6648c60de0e3d4da2eb60e8d45d12e/SharpLink/LavalinkManager.cs#L173-L175

**Comment by NovusTheory** [comment]
Fixed in 59abd51f3038b7b56d6c94e9524cc41d7f2be45a
