### ISSUE TITLE
VoiceChannel isn't updated when moved to another channel by a user in the guild.

### ISSUE THREAD

**Issue by jdcunningham** [Devoxin/SharpLink#22]
`LavalinkPlayer.VoiceChannel` is only set during the initialization of the player.

https://github.com/Devoxin/SharpLink/blob/d52c2eea5aa8923f85f8dc515b08259ffefc0672/SharpLink/LavalinkPlayer.cs#L19-L26

It should be updated whenever `baseDiscordClient.UserVoiceStateUpdated` is invoked.

https://github.com/Devoxin/SharpLink/blob/d52c2eea5aa8923f85f8dc515b08259ffefc0672/SharpLink/LavalinkManager.cs#L73-L101

A current workaround for this is to just get the current guild user's voice channel.

I'm sorry if I'm wrong, this is my first time doing anything like this. Please be gentle.

**Comment by jdcunningham** [comment]
I don't know if there's a way to link an issue to a pull request, so here's my pr for this issue. https://github.com/Devoxin/SharpLink/pull/23

**Comment by Adomix** [comment]
I may be missing the point but to set the channel you're supposed to get the users current channel (or pull one by ID).

**Comment by jdcunningham** [comment]
> I may be missing the point but to set the channel you're supposed to get the users current channel (or pull one by ID).

The VoiceChannel variable inside of LavalinkPlayer would be incorrect if a user inside the guild moves it to another channel. Yes, you can just get the current user's channel (which I mentioned), but if that is the case, VoiceChannel shouldn't be a public variable if we can't use it reliably to get what channel the player is actually in.
