### ISSUE TITLE
Possible problematic code in VoiceServerUpdated

### ISSUE THREAD

**Issue by NovusTheory** [Devoxin/SharpLink#5]
https://github.com/Devoxin/SharpLink/blob/fd5de3e76c1f8494efadf34d7ef6afb93297a20c/SharpLink/LavalinkManager.cs#L37

The code above may fail if a player doesn't exist. Currently by the looks it likely won't affect the library but still causes an exception to be thrown if the player doesn't exist. This code is implying that VoiceServerUpdated was fired in correlation with using SharpLink rather than externally Although this code might not be fired without the use of SharpLink it's good to know about this "bug" and to just patch it up

**Comment by Devoxin** [comment]
Fixed in cd656c7fbff766ad4dc2746adc6c7d8993bfcd6b
